Q_1
AbhiSeCode/testing pull request #2
Opened 2021-05-26 05:57 UTC by AbhiSeCode

2021-05-26 11:04 UTC, iamprashanttyagi requested changes
use as same response for all the API whether it is success or error:
example:
```
{
     success: 1,
     message: "any message" or "any error message",
     data: {} || []
}
```

2021-05-26 11:04 UTC, iamprashanttyagi commented on models/newUser.js
> +})
add salt to the hash 
and that salt will also store in database

2021-05-26 11:04 UTC, iamprashanttyagi commented on package.json
> +  },
add a start script

2021-05-26 12:12 UTC, AbhiSeCode commented on middlewares/authUser.js
> +       next(err)
In the route where it will be called.

2021-05-26 12:19 UTC, AbhiSeCode commented on middlewares/authUser.js
> +const NewUser = require('../models/newUser')
"NewUser" is to avoid naming in Mongodb collection as Previous(nodejs question) already have a user and userprofile collections.

2021-05-27 06:01 UTC, iamprashanttyagi requested changes

2021-05-27 06:01 UTC, iamprashanttyagi commented on models/newUser.js
> +const NewUser = mongoose.model("newUser", newUserSchema);
change the `newUser` to `user` as this collection is for user

2021-05-27 06:49 UTC, ashutoh-excel2011 approved these changes

2021-05-27 06:50 UTC, iamprashanttyagi approved these changes

2021-05-27 07:15 UTC, merged